import { Spell } from "../../types/spells";

export const available_spells: Spell[] = [
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    casting_time: "1 action",
    range: "150 feet",
    components: "V, S, M (a tiny ball of bat guano and sulfur)",
    duration: "Instantaneous",
    concentration: false,
    bonus_action: false,
    ritual: false,
    description:
      "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.",
    classes: ["Sorcerer", "Wizard"],
    subclasses: ["Artillerist", "Light Domain"],
    prepared: false,
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    casting_time: "1 reaction",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    concentration: false,
    bonus_action: false,
    ritual: false,
    description:
      "An invisible barrier of magical force appears and protects you.",
    classes: ["Sorcerer", "Wizard"],
    subclasses: [],
    prepared: false,
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    casting_time: "1 action",
    range: "30 feet",
    components: "V, S",
    duration: "1 minute",
    concentration: false,
    bonus_action: false,
    ritual: false,
    description:
      "A spectral, floating hand appears at a point you choose within range.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    subclasses: [],
    prepared: false,
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Evocation",
    casting_time: "1 bonus action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    bonus_action: true,
    ritual: false,
    description:
      "A creature of your choice that you can see within range regains hit points.",
    classes: ["Bard", "Cleric", "Druid"],
    subclasses: [],
    prepared: true,
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    casting_time: "1 action",
    range: "30 feet",
    components: "V, S, M (a sprinkling of holy water)",
    duration: "Concentration, up to 1 minute",
    concentration: true,
    bonus_action: false,
    ritual: false,
    description: "You bless up to three creatures of your choice within range.",
    classes: ["Cleric", "Paladin"],
    subclasses: [],
    prepared: true,
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "Divination",
    casting_time: "1 action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    concentration: true,
    bonus_action: false,
    ritual: true,
    description:
      "For the duration, you sense the presence of magic within 30 feet of you.",
    classes: [
      "Bard",
      "Cleric",
      "Druid",
      "Paladin",
      "Ranger",
      "Sorcerer",
      "Wizard",
    ],
    subclasses: [],
    prepared: true,
  },
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    casting_time: "1 bonus action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    concentration: false,
    bonus_action: true,
    ritual: false,
    description:
      "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    subclasses: [],
    prepared: false,
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "Evocation",
    casting_time: "1 bonus action",
    range: "60 feet",
    components: "V, S",
    duration: "1 minute",
    concentration: false,
    bonus_action: true,
    ritual: false,
    description:
      "You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again.",
    classes: ["Cleric"],
    subclasses: [],
    prepared: false,
  },
];
